### ISSUE TITLE
Pack: packing library

### ISSUE THREAD

**Issue by zkat** [orogene/orogene#80]
We need to be able to pack tarballs from package directories.

## TODO

* [x] Generate list of files to pack, following standard NPM rules ( #69 )
* [x] Generate a tarball from files (please use [`async-tar`](https://docs.rs/async-tar))
* [ ] Display tarball metadata on pack
* [ ] bundleDependencies support
